# Generated by Django 3.1.2 on 2020-10-11 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20201011_0556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='phno',
            new_name='phone',
        ),
    ]
