# Generated by Django 3.1.2 on 2020-10-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='firmname',
            field=models.CharField(default='', max_length=50),
        ),
    ]
