# Generated by Django 3.1.2 on 2020-10-28 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_customer_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='balance',
            new_name='wallet_balance',
        ),
    ]
