# Generated by Django 3.1.2 on 2020-10-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20201028_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='deal',
            field=models.BooleanField(default=False),
        ),
    ]
