# Generated by Django 3.1.2 on 2020-10-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_customer_deal'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ratings',
            field=models.FloatField(default=1.0),
        ),
    ]
